// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0AKGEYeHXerszRqNrnDwdoJLSyNVDp8',
    appId: '1:916110417236:web:76e4d3bbb393492d3abcc1',
    messagingSenderId: '916110417236',
    projectId: 'personal-finance-manager-f59fa',
    authDomain: 'personal-finance-manager-f59fa.firebaseapp.com',
    storageBucket: 'personal-finance-manager-f59fa.firebasestorage.app',
    measurementId: 'G-PXS237HS4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu8-pW7XB8oqYaaO9Pp-O03C3i2fVI-JA',
    appId: '1:916110417236:android:5d1708c8ff4bb0533abcc1',
    messagingSenderId: '916110417236',
    projectId: 'personal-finance-manager-f59fa',
    storageBucket: 'personal-finance-manager-f59fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDGMF1RbxQ_lWpRHegseX3IKBJnrR7xRM',
    appId: '1:916110417236:ios:846b4aaa5a28ee773abcc1',
    messagingSenderId: '916110417236',
    projectId: 'personal-finance-manager-f59fa',
    storageBucket: 'personal-finance-manager-f59fa.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDGMF1RbxQ_lWpRHegseX3IKBJnrR7xRM',
    appId: '1:916110417236:ios:846b4aaa5a28ee773abcc1',
    messagingSenderId: '916110417236',
    projectId: 'personal-finance-manager-f59fa',
    storageBucket: 'personal-finance-manager-f59fa.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0AKGEYeHXerszRqNrnDwdoJLSyNVDp8',
    appId: '1:916110417236:web:7f68e2fee1f02c0b3abcc1',
    messagingSenderId: '916110417236',
    projectId: 'personal-finance-manager-f59fa',
    authDomain: 'personal-finance-manager-f59fa.firebaseapp.com',
    storageBucket: 'personal-finance-manager-f59fa.firebasestorage.app',
    measurementId: 'G-7FBN22FDWD',
  );
}
